version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: ors-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project10_adv
      MYSQL_USER: rajat
      MYSQL_PASSWORD: Indore@123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ors-network

  # Spring Boot Backend (Development)
  backend:
    build:
      context: ./projectORS
      dockerfile: Dockerfile
    container_name: ors-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/project10_adv?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: rajat
      SPRING_DATASOURCE_PASSWORD: Indore@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      # JWT Configuration
      JWT_SECRET: RaysTechSecretKey2024
      # Mail Configuration
      SPRING_MAIL_USERNAME: test@gmail.com
      SPRING_MAIL_PASSWORD: test_password
    ports:
      - "8084:8084"
    depends_on:
      - database
    networks:
      - ors-network
    volumes:
      - backend_logs:/app/logs

  # Angular Frontend (Development)
  frontend:
    build:
      context: ./ORSProject10-UI
      dockerfile: Dockerfile
    container_name: ors-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - ors-network


volumes:
  mysql_data:
    driver: local
  backend_logs:
    driver: local

networks:
  ors-network:
    driver: bridge
