version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: ors-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project10_adv
      MYSQL_USER: rajat
      MYSQL_PASSWORD: Indore@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployment/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ors-network

  # Spring Boot Backend (Development)
  backend:
    build:
      context: ./projectORS
      dockerfile: Dockerfile
    container_name: ors-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: project10_adv
      DB_USERNAME: rajat
      DB_PASSWORD: Indore@123
      JWT_SECRET: RaysTechSecretKey2024
      MAIL_USERNAME: test@gmail.com
      MAIL_PASSWORD: test_password
    ports:
      - "8084:8084"
    depends_on:
      - database
    networks:
      - ors-network
    volumes:
      - backend_logs:/app/logs

  # Angular Frontend (Development)
  frontend:
    build:
      context: ./ORSProject10-UI
      dockerfile: Dockerfile
    container_name: ors-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - ors-network


volumes:
  mysql_data:
    driver: local
  backend_logs:
    driver: local

networks:
  ors-network:
    driver: bridge
